import type { Attribute, CharacterData, SkillDef, Weapon } from "./types";

export const GM_PIN = "1234";

export const ALL_SKILLS: SkillDef[] = [
    { name: "Heavy Machinery", attr: "strength" },
    { name: "Stamina", attr: "strength" },
    { name: "Close Combat", attr: "strength" },
    { name: "Mobility", attr: "agility" },
    { name: "Ranged Combat", attr: "agility" },
    { name: "Piloting", attr: "agility" },
    { name: "Observation", attr: "wits" },
    { name: "Comtech", attr: "wits" },
    { name: "Survival", attr: "wits" },
    { name: "Command", attr: "empathy" },
    { name: "Manipulation", attr: "empathy" },
    { name: "Medical Aid", attr: "empathy" },
];

export const ATTR_LABELS: Record<Attribute, string> = {
    strength: "Strength",
    agility: "Agility",
    wits: "Wits",
    empathy: "Empathy",
};

export const ATTR_COLORS: Record<Attribute, string> = {
    strength: "text-red-400",
    agility: "text-green-400",
    wits: "text-blue-400",
    empathy: "text-yellow-400",
};

export const TALENT_DESCRIPTIONS: Record<string, string> = {
    "Bodyguard":
        "When you are at ENGAGED range with a buddy or another designated person, you can take the hit for them. When your buddy is attacked, you can choose to be the target instead. You must declare this before the attack roll is made.",
    "Field Surgeon":
        "When you perform MEDICAL AID on someone who has suffered a critical injury, you get a +2 modification. If you successfully treat the critical injury, the patient immediately recovers 1 Health Point.",
    "Banter":
        "You can push any skill roll based on EMPATHY, even if you are not stressed. When you push, you do not gain a stress level.",
    "Weapon's Specialist (RPG)":
        "Choose one weapon type. When using a weapon of this type, your attacks deal +1 additional damage. Dante's chosen weapon: M5 RPG Launcher.",
    "Past the Limit":
        "When your stress level reaches the breaking point, you don't have to make a Panic Roll. Instead, the next time your Stress Level is increased, you have to make a Panic Roll as usual.",
    "Hard Hitter":
        "When you cause damage with a close combat attack, you deal +1 additional damage.",
    "Hothead":
        "You can push any skill roll based on STRENGTH, even if you are not stressed. When you push, you do not gain a stress level.",
    "Menacing":
        "When you try to intimidate someone, you get a +2 modification to MANIPULATION.",
    "Overkill":
        "When you inflict damage with a ranged weapon attack, you can choose to keep rolling on any sixes rolled. Each additional six adds +1 damage, but you can only reroll each die once.",
    "Nerves of Steel":
        "You can never gain more than one Stress Level from a single event.",
    "Field Commander":
        "When you give a command to another PC or NPC, you can push your COMMAND roll even if you are not stressed. When you push, you do not gain a stress level.",
};

export const RULEBOOK_WEAPONS: Weapon[] = [
    { name: "M4A3 Service Pistol", bonus: 2, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
    { name: ".357 Magnum", bonus: 1, damage: 2, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
    { name: "Rexim RXF-M5 EVA Pistol", bonus: 1, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
    { name: "Watatsumi DV-303 Bolt Gun", bonus: 0, damage: 3, range: "Short", fullAuto: false, skill: "Ranged Combat" },
    { name: "M41A Pulse Rifle", bonus: 1, damage: 2, range: "Long", fullAuto: true, skill: "Ranged Combat" },
    { name: "AK-4047", bonus: 0, damage: 2, range: "Long", fullAuto: true, skill: "Ranged Combat" },
    { name: "M42A Scope Rifle", bonus: 2, damage: 2, range: "Extreme", fullAuto: false, skill: "Ranged Combat" },
    { name: "Model 37A2 12 Gauge", bonus: 2, damage: 3, range: "Short", fullAuto: false, skill: "Ranged Combat" },
    { name: "ASSO-400 Harpoon Gun", bonus: 0, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
    { name: "XM99A Phased Plasma Pulse Rifle", bonus: 0, damage: 4, range: "Extreme", fullAuto: false, skill: "Ranged Combat" },
    { name: "U1 Grenade Launcher", bonus: 1, damage: 9, range: "Long", fullAuto: false, skill: "Ranged Combat" },
    { name: "M41AE2 Heavy Pulse Rifle", bonus: 1, damage: 3, range: "Extreme", fullAuto: true, skill: "Ranged Combat" },
    { name: "M56 Smartgun", bonus: 3, damage: 3, range: "Long", fullAuto: true, skill: "Ranged Combat" },
    { name: "M240 Incinerator Unit", bonus: 0, damage: 2, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
    { name: "UA 571-C Sentry Gun", bonus: 2, damage: 4, range: "Extreme", fullAuto: true, skill: "Ranged Combat" },
    { name: "G2 Electroshock Grenade", bonus: 0, damage: 0, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
    { name: "M5 RPG Launcher", bonus: 1, damage: 9, range: "Extreme", fullAuto: false, skill: "Ranged Combat" },
    { name: "M40 HEDP Grenade", bonus: 0, damage: 9, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
    { name: "Unarmed", bonus: 0, damage: 1, range: "Engaged", fullAuto: false, skill: "Close Combat" },
    { name: "Blunt Instrument", bonus: 1, damage: 1, range: "Engaged", fullAuto: false, skill: "Close Combat" },
    { name: "Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
    { name: "Combat Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
    { name: "Stun Baton", bonus: 1, damage: 1, range: "Engaged", fullAuto: false, skill: "Close Combat" },
    { name: "Cutting Torch", bonus: 0, damage: 3, range: "Engaged", fullAuto: false, skill: "Close Combat" },
];

export const INITIAL_CHARACTERS: CharacterData[] = [
    {
        id: "chaplain",
        name: "CHAPLAIN",
        rank: "Warrant Officer",
        career: "Medic",
        fullName: "Chaplain",
        age: 22,
        personality: "Bipolar",
        strength: 6,
        agility: 6,
        wits: 4,
        empathy: 4,
        health: 6,
        maxHealth: 6,
        stress: 0,
        skills: {
            "Heavy Machinery": 2,
            Piloting: 2,
            Observation: 2,
            Comtech: 4,
            "Medical Aid": 4,
        },
        talent1: "Bodyguard",
        talent2: "Field Surgeon",
        buddy: "Mason",
        rival: "",
        signatureItem: "Sticky pad of false Charlie Chaplin mustaches",
        gear: [
            "M314 Motion Tracker",
            "Electronic Tools",
            "Cutting Torch",
            "Medkit",
            "Field Surgeon Kit",
            "Ammo satchel",
        ],
        weapons: [
            { name: "Cutting Torch", bonus: 0, damage: 3, range: "Engaged", fullAuto: false, skill: "Close Combat" },
        ],
        armor: "None",
        armorRating: 0,
        encumbrance: 12,
        criticalInjuries: [],
        assignedUserId: null,
        android: true,
    },
    {
        id: "dante",
        name: "DANTE",
        rank: "Private First Class",
        career: "Colonial Marine",
        fullName: "Ruth Anne Dante",
        age: 33,
        personality: "Talkative",
        strength: 5,
        agility: 4,
        wits: 3,
        empathy: 2,
        health: 7,
        maxHealth: 7,
        stress: 0,
        skills: {
            "Heavy Machinery": 3,
            "Close Combat": 2,
            Stamina: 2,
            "Ranged Combat": 4,
            Mobility: 1,
        },
        talent1: "Banter",
        talent2: "Weapon's Specialist (RPG)",
        buddy: "Hammer",
        rival: "Chaplain",
        assignedUserId: null,
        android: false,
        signatureItem: "Folded Discharge Papers",
        gear: [
            "M5 RPG Launcher",
            "M41A Pulse Rifle with U1 Grenade Launcher",
            "Cutting Torch",
            "M4A3 Service Pistol",
            "Combat Knife",
            "M3 Personnel Armor",
        ],
        weapons: [
            { name: "M5 RPG Launcher", bonus: 1, damage: 9, range: "Extreme", fullAuto: false, skill: "Ranged Combat" },
            { name: "M41A Pulse Rifle", bonus: 1, damage: 2, range: "Long", fullAuto: true, skill: "Ranged Combat" },
            { name: "U1 Grenade Launcher", bonus: 1, damage: 9, range: "Long", fullAuto: false, skill: "Ranged Combat" },
            { name: "M4A3 Service Pistol", bonus: 2, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "Cutting Torch", bonus: 0, damage: 3, range: "Engaged", fullAuto: false, skill: "Close Combat" },
            { name: "Combat Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
        ],
        armor: "M3 P. Armor",
        armorRating: 6,
        encumbrance: 10,
        criticalInjuries: [],
    },
    {
        id: "iona",
        name: "IONA",
        rank: "Sergeant",
        career: "Colonial Marine",
        fullName: "Kale Iona",
        age: 36,
        personality: "Nervous",
        strength: 4,
        agility: 3,
        wits: 3,
        empathy: 4,
        health: 4,
        maxHealth: 4,
        stress: 0,
        skills: {
            "Close Combat": 2,
            Stamina: 3,
            "Ranged Combat": 4,
            Mobility: 1,
            Piloting: 2,
            Command: 1,
        },
        talent1: "Banter",
        talent2: "Past the Limit",
        buddy: "Zmijewski",
        rival: "Chaplain",
        assignedUserId: null,
        android: false,
        signatureItem: "Postcard",
        gear: [
            "M56 Smartgun",
            "M3 Personnel Armor",
            "M4A3 Service Pistol",
            "Combat Knife",
        ],
        weapons: [
            { name: "M56 Smartgun", bonus: 3, damage: 3, range: "Long", fullAuto: true, skill: "Ranged Combat" },
            { name: "M4A3 Service Pistol", bonus: 2, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "Combat Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
        ],
        armor: "M3 P. Armor",
        armorRating: 6,
        encumbrance: 8,
        criticalInjuries: [],
    },
    {
        id: "zmijewski",
        name: "ZMIJEWSKI",
        rank: "Private First Class",
        career: "Colonial Marine",
        fullName: "Stanley T. Zmijewski",
        age: 34,
        personality: "Agitated",
        strength: 4,
        agility: 5,
        wits: 3,
        empathy: 2,
        health: 4,
        maxHealth: 4,
        stress: 0,
        skills: {
            "Close Combat": 3,
            Stamina: 1,
            "Ranged Combat": 3,
            Mobility: 1,
            Piloting: 1,
            Observation: 2,
            Survival: 2,
        },
        talent1: "Hard Hitter",
        talent2: "Hothead",
        buddy: "",
        rival: "Hammer",
        assignedUserId: null,
        android: false,
        signatureItem: "Worn leather belt with concealed knife",
        gear: [
            "M41A Pulse Rifle with M316 Motion Tracker",
            "Incinerator unit",
            "M4A3 Service Pistol",
            "Combat Knife",
            "M3 Personnel Armor",
        ],
        weapons: [
            { name: "M41A Pulse Rifle", bonus: 1, damage: 2, range: "Long", fullAuto: true, skill: "Ranged Combat" },
            { name: "M4A3 Service Pistol", bonus: 2, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "M240 Incinerator Unit", bonus: 0, damage: 2, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "Combat Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
        ],
        armor: "M3 P. Armor",
        armorRating: 6,
        encumbrance: 8,
        criticalInjuries: [],
    },
    {
        id: "hammer",
        name: "HAMMER",
        rank: "Private",
        career: "Colonial Marine",
        fullName: "Nathaniel A.W. Hammer",
        age: 22,
        personality: "Psychotic",
        strength: 5,
        agility: 5,
        wits: 3,
        empathy: 1,
        health: 5,
        maxHealth: 5,
        stress: 0,
        skills: {
            "Close Combat": 4,
            Stamina: 3,
            "Ranged Combat": 4,
            Mobility: 1,
        },
        talent1: "Menacing",
        talent2: "Overkill",
        buddy: "Dante",
        rival: "Mason",
        assignedUserId: null,
        android: false,
        signatureItem: "Four X-Stim Syringes",
        gear: [
            "M56 Smartgun",
            "M3 Personnel Armor",
            "4x M40 HEDP Grenades",
            "M4A3 Service Pistol",
            "Combat Knife",
        ],
        weapons: [
            { name: "M56 Smartgun", bonus: 3, damage: 3, range: "Long", fullAuto: true, skill: "Ranged Combat" },
            { name: "M4A3 Service Pistol", bonus: 2, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "M40 HEDP Grenade", bonus: 0, damage: 9, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "Combat Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
        ],
        armor: "M3 P. Armor",
        armorRating: 6,
        encumbrance: 10,
        criticalInjuries: [],
    },
    {
        id: "mason",
        name: "MASON",
        rank: "Gunnery Sergeant",
        career: "Colonial Marine",
        fullName: "Luca Mason",
        age: 42,
        personality: "Meticulous",
        strength: 4,
        agility: 4,
        wits: 3,
        empathy: 3,
        health: 4,
        maxHealth: 4,
        stress: 0,
        skills: {
            "Close Combat": 2,
            Stamina: 2,
            "Ranged Combat": 3,
            Mobility: 1,
            Observation: 1,
            Command: 1,
            "Medical Aid": 2,
        },
        talent1: "Nerves of Steel",
        talent2: "Overkill",
        buddy: "Chaplain",
        rival: "Hammer",
        assignedUserId: null,
        android: false,
        signatureItem: "Colonial Marine Figure",
        gear: [
            "M41A Pulse Rifle with U1 Grenade Launcher",
            "M4A3 Service Pistol",
            "Combat Knife",
            "M3 Personnel Armor",
            "CBRN Detection Kit",
            "Incinerator unit",
            "Neversleep blister pack",
        ],
        weapons: [
            { name: "M41A Pulse Rifle", bonus: 1, damage: 2, range: "Long", fullAuto: true, skill: "Ranged Combat" },
            { name: "U1 Grenade Launcher", bonus: 1, damage: 9, range: "Long", fullAuto: false, skill: "Ranged Combat" },
            { name: "M4A3 Service Pistol", bonus: 2, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "M240 Incinerator Unit", bonus: 0, damage: 2, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "Combat Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
        ],
        armor: "M3 P. Armor",
        armorRating: 6,
        encumbrance: 8,
        criticalInjuries: [],
    },
    {
        id: "silva",
        name: "SILVA",
        rank: "Captain",
        career: "Officer",
        fullName: "Beatriz Silva",
        age: 43,
        personality: "Authoritative",
        strength: 3,
        agility: 3,
        wits: 4,
        empathy: 4,
        health: 3,
        maxHealth: 3,
        stress: 0,
        skills: {
            "Close Combat": 2,
            Stamina: 2,
            "Ranged Combat": 3,
            Mobility: 2,
            Command: 3,
            Manipulation: 2,
        },
        talent1: "Field Commander",
        talent2: "Past the Limit",
        buddy: "Hammer",
        rival: "Iona",
        assignedUserId: null,
        android: false,
        signatureItem: "Pack of Smokes and a Lighter",
        gear: [
            "M41A Pulse Rifle",
            "Seegson P-DAT",
            "M4A3 Service Pistol",
            "Combat Knife",
            "M3 Personnel Armor",
        ],
        weapons: [
            { name: "M41A Pulse Rifle", bonus: 1, damage: 2, range: "Long", fullAuto: true, skill: "Ranged Combat" },
            { name: "M4A3 Service Pistol", bonus: 2, damage: 1, range: "Medium", fullAuto: false, skill: "Ranged Combat" },
            { name: "Combat Knife", bonus: 0, damage: 2, range: "Engaged", fullAuto: false, skill: "Close Combat" },
        ],
        armor: "M3 P. Armor",
        armorRating: 6,
        encumbrance: 6,
        criticalInjuries: [],
    },
];
